# Generated by Django 5.0.7 on 2024-07-17 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IMSapp', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='base.patient'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMSapp.productcategory'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='base.patient'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMSapp.product'),
        ),
        migrations.AddField(
            model_name='billing',
            name='purchases',
            field=models.ManyToManyField(to='IMSapp.purchase'),
        ),
        migrations.AddField(
            model_name='purchase_products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMSapp.productcategory'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patient'),
        ),
        migrations.AddField(
            model_name='purchase_products',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMSapp.supplier'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMSapp.supplier'),
        ),
    ]
