# Generated by Django 5.0.6 on 2024-06-30 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IMSapp.productcategory'),
        ),
        migrations.AddField(
            model_name='purchase_products',
            name='department',
            field=models.ManyToManyField(to='IMSapp.department'),
        ),
    ]
