# Generated by Django 5.0.6 on 2024-06-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0003_purchase_products_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='floor',
        ),
    ]
