# Generated by Django 5.0.7 on 2024-07-17 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0004_alter_product_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_products',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IMSapp.department'),
        ),
    ]
