# Generated by Django 5.0.6 on 2024-07-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0005_remove_product_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchased_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
