# Generated by Django 5.0.7 on 2024-07-17 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0005_purchase_products_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_products',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMSapp.department'),
        ),
    ]
