# Generated by Django 5.0.6 on 2024-07-06 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0006_purchase_purchased_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchased_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
