# Generated by Django 5.0.7 on 2024-07-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0008_remove_product_supplier_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='total',
        ),
    ]
