# Generated by Django 5.0.7 on 2024-07-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0010_billing_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
