# Generated by Django 5.0.7 on 2024-07-12 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0011_delete_billing'),
        ('base', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='base.patient')),
                ('purchases', models.ManyToManyField(to='IMSapp.purchase')),
            ],
        ),
    ]
