# Generated by Django 5.0.7 on 2024-07-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0012_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='total',
        ),
    ]
