# Generated by Django 5.0.7 on 2024-07-12 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0013_remove_billing_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_products',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(help_text='Enter a 10-digit contact number', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
