# Generated by Django 5.0.7 on 2024-07-12 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0014_purchase_products_total_alter_supplier_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_products',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IMSapp.department'),
        ),
        migrations.AlterField(
            model_name='purchase_products',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchase_products',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase_products',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IMSapp.supplier'),
        ),
        migrations.AlterField(
            model_name='purchase_products',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
