# Generated by Django 5.0.7 on 2024-07-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0016_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
