# Generated by Django 5.0.7 on 2024-07-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_medicalrecord_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
