# Generated by Django 5.0.7 on 2024-07-17 09:25

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='schedule',
            field=models.DateField(validators=[base.validators.validate_appointment_date]),
        ),
    ]
