# Generated by Django 5.0.7 on 2024-07-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_staff_availability_alter_patient_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='availability',
            field=models.BooleanField(),
        ),
    ]
