# Generated by Django 5.0.7 on 2024-07-18 04:59

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_staff_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='Abc123###123', max_length=300, validators=[base.validators.CustomPasswordValidator]),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='Abc123###123', max_length=300, validators=[base.validators.CustomPasswordValidator]),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='Abc123###123', max_length=300, validators=[base.validators.CustomPasswordValidator]),
        ),
    ]
