# Generated by Django 5.0.7 on 2024-07-18 05:00

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_doctor_password_patient_password_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=300, validators=[base.validators.CustomPasswordValidator]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=300, validators=[base.validators.CustomPasswordValidator]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=300, validators=[base.validators.CustomPasswordValidator]),
        ),
    ]
