# Generated by Django 5.0.7 on 2024-07-18 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_doctor_password_alter_patient_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(default='Unknown Position', on_delete=django.db.models.deletion.CASCADE, to='base.staff_position'),
        ),
    ]
