# Generated by Django 5.0.7 on 2024-07-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_staff_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='password',
        ),
    ]
