# Generated by Django 5.0.7 on 2024-07-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_doctor_password_alter_doctor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
